In [4]:
import pandas as pd
print("succesfully imported librabrary")

succesfully imported librabrary

In [10]:
df=pd.read_csv('student_performance.csv')
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [11]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [12]:
df.shape

(30, 13)

In [17]:
df.shape[0]

30

In [14]:
df.shape[1]

13

In [18]:
df.iloc[:,4]

0     Computer Science
1     Computer Science
2          Electronics
3           Mechanical
4     Computer Science
5          Electronics
6                Civil
7     Computer Science
8           Mechanical
9     Computer Science
10         Electronics
11               Civil
12    Computer Science
13          Mechanical
14    Computer Science
15         Electronics
16               Civil
17    Computer Science
18          Mechanical
19    Computer Science
20         Electronics
21    Computer Science
22               Civil
23          Mechanical
24    Computer Science
25         Electronics
26    Computer Science
27               Civil
28          Mechanical
29    Computer Science
Name: department, dtype: object

In [19]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [23]:
df.values.tolist()

[[1001,
  'Aarav Sharma',
  19,
  'Male',
  'Computer Science',
  2,
  85,
  78,
  72,
  91,
  92,
  'Mumbai',
  2023],
 [1002,
  'Priya Patel',
  20,
  'Female',
  'Computer Science',
  2,
  76,
  82,
  88,
  79,
  87,
  'Ahmedabad',
  2023],
 [1003,
  'Rohit Verma',
  19,
  'Male',
  'Electronics',
  2,
  65,
  74,
  61,
  55,
  78,
  'Delhi',
  2023],
 [1004,
  'Sneha Reddy',
  20,
  'Female',
  'Mechanical',
  2,
  70,
  80,
  75,
  48,
  95,
  'Hyderabad',
  2023],
 [1005,
  'Arjun Nair',
  19,
  'Male',
  'Computer Science',
  2,
  92,
  88,
  81,
  95,
  90,
  'Kochi',
  2023],
 [1006,
  'Meera Joshi',
  20,
  'Female',
  'Electronics',
  2,
  58,
  66,
  70,
  52,
  72,
  'Pune',
  2023],
 [1007,
  'Kiran Kumar',
  21,
  'Male',
  'Civil',
  2,
  73,
  69,
  65,
  40,
  85,
  'Bangalore',
  2023],
 [1008,
  'Divya Singh',
  19,
  'Female',
  'Computer Science',
  2,
  88,
  91,
  84,
  93,
  96,
  'Lucknow',
  2023],
 [1009,
  'Rahul Mishra',
  20,
  'Male',
  'Mechanical',
  2,
  62,
  71,
  58,
  45,
  68,
  'Varanasi',
  2023],
 [1010,
  'Ananya Das',
  19,
  'Female',
  'Computer Science',
  2,
  95,
  89,
  90,
  97,
  98,
  'Kolkata',
  2023],
 [1011,
  'Vikram Iyer',
  20,
  'Male',
  'Electronics',
  2,
  80,
  75,
  68,
  72,
  83,
  'Chennai',
  2023],
 [1012,
  'Pooja Gupta',
  19,
  'Female',
  'Civil',
  2,
  67,
  72,
  79,
  44,
  80,
  'Jaipur',
  2023],
 [1013,
  'Suresh Rao',
  21,
  'Male',
  'Computer Science',
  2,
  83,
  86,
  77,
  88,
  88,
  'Mysore',
  2023],
 [1014,
  'Kavya Nambiar',
  20,
  'Female',
  'Mechanical',
  2,
  74,
  78,
  82,
  51,
  91,
  'Thrissur',
  2023],
 [1015,
  'Ajay Tiwari',
  19,
  'Male',
  'Computer Science',
  2,
  71,
  69,
  64,
  76,
  75,
  'Bhopal',
  2023],
 [1016,
  'Ritu Agarwal',
  20,
  'Female',
  'Electronics',
  2,
  87,
  83,
  86,
  69,
  93,
  'Agra',
  2023],
 [1017,
  'Manoj Pandey',
  21,
  'Male',
  'Civil',
  2,
  56,
  61,
  55,
  38,
  65,
  'Patna',
  2023],
 [1018,
  'Swati Kulkarni',
  19,
  'Female',
  'Computer Science',
  2,
  90,
  87,
  85,
  92,
  94,
  'Nagpur',
  2023],
 [1019,
  'Deepak Chauhan',
  20,
  'Male',
  'Mechanical',
  2,
  68,
  73,
  62,
  49,
  77,
  'Dehradun',
  2023],
 [1020,
  'Nisha Kapoor',
  19,
  'Female',
  'Computer Science',
  2,
  79,
  84,
  81,
  83,
  89,
  'Chandigarh',
  2023],
 [1021,
  'Harish Pillai',
  20,
  'Male',
  'Electronics',
  2,
  64,
  70,
  67,
  58,
  74,
  'Thiruvananthapuram',
  2023],
 [1022,
  'Tanvi Mehta',
  19,
  'Female',
  'Computer Science',
  2,
  93,
  90,
  88,
  96,
  97,
  'Surat',
  2023],
 [1023,
  'Sanjay Dubey',
  21,
  'Male',
  'Civil',
  2,
  61,
  66,
  59,
  42,
  70,
  'Allahabad',
  2023],
 [1024,
  'Preeti Saxena',
  20,
  'Female',
  'Mechanical',
  2,
  77,
  81,
  76,
  53,
  86,
  'Kanpur',
  2023],
 [1025,
  'Amit Bose',
  19,
  'Male',
  'Computer Science',
  2,
  86,
  82,
  79,
  89,
  91,
  'Kolkata',
  2023],
 [1026,
  'Rekha Nair',
  20,
  'Female',
  'Electronics',
  2,
  72,
  77,
  73,
  63,
  82,
  'Kochi',
  2023],
 [1027,
  'Gaurav Shukla',
  21,
  'Male',
  'Computer Science',
  2,
  84,
  79,
  75,
  87,
  87,
  'Lucknow',
  2023],
 [1028,
  'Sunita Pillai',
  19,
  'Female',
  'Civil',
  2,
  60,
  65,
  68,
  39,
  73,
  'Thiruvananthapuram',
  2023],
 [1029,
  'Nitin Jain',
  20,
  'Male',
  'Mechanical',
  2,
  75,
  76,
  70,
  50,
  84,
  'Indore',
  2023],
 [1030,
  'Akanksha Yadav',
  19,
  'Female',
  'Computer Science',
  2,
  91,
  93,
  87,
  94,
  95,
  'Agra',
  2023]]

In [27]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [28]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [29]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [34]:
import numpy as np
df.loc[0:4, 'math_score'] = np.nan

In [35]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
df['department'].unique()

array(['Computer Science', 'Electronics', 'Mechanical', 'Civil'],
      dtype=object)

In [37]:
df['department'].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [38]:
df['gender'].value_counts()

gender
Male      15
Female    15
Name: count, dtype: int64

In [39]:
df['city'].value_counts()7

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [45]:
cs_students=df[df['department']=='Computer Science']
print(f"number of computer science student: {len(cs_students)}")
print("\nComputer Science  Students:")
print(cs_students)

number of computer science student: 13

Computer Science  Students:
    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2
9         1010      Ananya Das   19  Female  Computer Science         2
12        1013      Suresh Rao   21    Male  Computer Science         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0          NaN             78             72                 91
1          NaN             82             88                 79
4          NaN             88             81                 95
7         88.0             91             84                 93
9         95.0             89             90                 97
12        83.0             86             77                 88
14        71.0             69             64                 76
17        90.0             87             85                 92
19        79.0             84             81                 83
21        93.0             90             88                 96
24        86.0             82             79                 89
26        84.0             79             75                 87
29        91.0             93             87                 94

    attendance_percentage        city  admission_year
0                      92      Mumbai            2023
1                      87   Ahmedabad            2023
4                      90       Kochi            2023
7                      96     Lucknow            2023
9                      98     Kolkata            2023
12                     88      Mysore            2023
14                     75      Bhopal            2023
17                     94      Nagpur            2023
19                     89  Chandigarh            2023
21                     97       Surat            2023
24                     91     Kolkata            2023
26                     87     Lucknow            2023
29                     95        Agra            2023

In [49]:
first=df[df['city'] == 'Chennai']['programming_score']
print(first)

10    72
Name: programming_score, dtype: int64

In [50]:
second=df[df['city'] == 'Mumbai']['programming_score']
print(second)

0    91
Name: programming_score, dtype: int64

In [58]:
high=df[df['attendance_percentage']<=75]
print(f"students with attendance below 75%: {len(high)}")

students with attendance below 75%: 7

In [60]:
df['total_score'] = df['math_score'] + df['science_score'] + df['programming_score']

In [61]:
print(df.loc[df['total_score'].idxmax()])

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                           95.0
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                         281.0
Name: 9, dtype: object

In [62]:
print(df.loc[df['total_score'].idxmin()])

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                       56.0
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total_score                     155.0
Name: 16, dtype: object